### ISSUE TITLE
Modify appveyor.yml to not build on README related changes

### ISSUE THREAD

**Issue by davidhayden** [davidhayden/Freelancer#10]
The [appveyor.yml reference](https://www.appveyor.com/docs/appveyor-yml/) and [commits filtering](https://www.appveyor.com/docs/how-to/filtering-commits/) docs mention options to skip builds when only certain files are touched.

```yaml
skip_commits:
  files:
    - dir/*
    - dir/*.md
    - full/path.txt
    - another/dir/here/
    - '**/*.html'
```

Build should be skipped when making changes to README and the assets used in the README.
